Repository THIP-TextHip/THIP-Web, pull requests merged in 2025-09, with the labels that each got.

#221 feat: 무한 스크롤 API 수정
  index.html
  src/api/books/getSavedBooks.ts
  src/components/common/BookSearchBottomSheet/BookList.tsx
  src/components/common/BookSearchBottomSheet/BookSearchBottomSheet.tsx
  src/components/common/BookSearchBottomSheet/useBookSearch.ts
Labels: ✨ Feature

#223 refactor: 좌우 스와이프 더 확실하게 차단
  index.html
Labels: 🐞 BugFix

#236 feat: rooms API 추가 연동 (방 나가기 / 기록 수정 / 투표 수정)
  src/api/record/updateRecord.ts
  src/api/record/updateVote.ts
  src/api/rooms/leaveRoom.ts
  src/components/memory/RecordItem/RecordItem.tsx
  src/components/pollwrite/PollCreationSection.tsx
  src/components/recordwrite/PageRangeSection.tsx
  src/components/recordwrite/RecordContentSection.tsx
  src/pages/groupDetail/ParticipatedGroupDetail.tsx
  src/pages/index.tsx
  src/pages/pollwrite/PollWrite.tsx
  src/pages/recordwrite/RecordWrite.tsx
  src/types/record.ts
Labels: ✨ Feature, 📬 API

#237 feat: presigned URL API 연동 및 이미지 업로드 방식 수정
  src/api/feeds/createFeed.ts
  src/api/feeds/getPresignedUrl.ts
  src/api/feeds/uploadToS3.ts
  src/hooks/useCreateFeed.ts
  src/pages/post/CreatePost.tsx
Labels: ✨ Feature

#233 fix: QA
  index.html
  package.json
  src/api/index.ts
  src/api/users/getUsers.ts
  src/components/common/Modal/MoreMenu.tsx
  src/components/feed/FollowList.tsx
  src/components/feed/UserProfileItem.tsx
  src/data/userData.ts
  src/pages/feed/Feed.tsx
  src/pages/feed/FollowerListPage.tsx
  src/pages/mypage/SavePage.tsx
  src/types/user.ts
Labels: 🐞 BugFix

#242 fix: 구글 애널리틱스 호출 함수 main.tsx에 추가
  src/main.tsx
Labels: 🐞 BugFix, 📃 Docs

#243 develp branch 작업내용 머지 : develop -> main
  src/main.tsx
Labels: 🌏 Deploy

#245 [FIX] 9월 2주차 QA 사항 - 지현
  src/components/members/MemberList.styled.ts
  src/components/members/MemberList.tsx
  src/components/memory/RecordItem/RecordItem.styled.ts
Labels: 🐞 BugFix

#247 fix: 기록장 투표 정보 퍼센트가 아닌 득표수로 표시되도록 수정
  src/components/memory/RecordItem/PollRecord.tsx
  src/pages/memory/Memory.tsx
  src/types/memory.ts
  src/types/record.ts
Labels: ✨ Feature

#249 [FIX] 9월 3주차 QA 사항 - 호준
  src/api/rooms/getJoinedRooms.ts
  src/api/rooms/getRoomDetail.ts
  src/api/rooms/getRoomPlaying.ts
  src/api/rooms/getRoomsByCategory.ts
  src/api/rooms/getSearchRooms.ts
  src/assets/common/back.svg
  src/assets/common/next.svg
  src/assets/common/searchChar.svg
  src/components/group/CompletedGroupModal.tsx
  src/components/group/MyGroupBox.tsx
  src/components/group/MyGroupCard.tsx
  src/components/group/MyGroupModal.tsx
  src/components/group/RecruitingGroupBox.tsx
  src/components/group/RecruitingGroupCarousel.tsx
  src/components/search/GroupSearchResult.tsx
  src/hooks/useInfiniteCarousel.ts
  src/pages/group/Group.tsx
  src/pages/groupDetail/GroupDetail.styled.ts
  src/pages/groupDetail/GroupDetail.tsx
  src/pages/groupSearch/GroupSearch.tsx
Labels: ✨ Feature, 🔨 Refactor

#253 [FIX] 9월 3주차 QA 사항 - 희용
  src/api/auth/getToken.ts
  src/api/index.ts
  src/api/notifications/getNotifications.ts
  src/api/users/deleteUsers.ts
  src/components/group/CompletedGroupModal.tsx
  src/components/group/GroupCard.tsx
  src/components/group/MyGroupBox.tsx
  src/hooks/useSocialLoginToken.ts
  src/pages/feed/Feed.tsx
  src/pages/group/Group.tsx
  src/pages/mypage/WithdrawPage.tsx
  src/pages/notice/Notice.tsx
  src/pages/signup/SignupGenre.tsx
  src/pages/signup/SignupNickname.tsx
Labels: ✨ Feature, 📬 API

#260 [FIX] 9월 3주차 2차 QA 사항 - 희용
  index.html
  package.json
  pnpm-lock.yaml
  src/api/notifications/postNotificationsCheck.ts
  src/lib/ga.ts
  src/main.tsx
  src/pages/memory/Memory.tsx
  src/pages/notice/Notice.tsx
Labels: 🐞 BugFix, 📃 Docs, ✨ Feature

#261 develp branch 작업내용 머지 : develop -> main
  index.html
  package.json
  pnpm-lock.yaml
  src/api/notifications/postNotificationsCheck.ts
  src/lib/ga.ts
  src/main.tsx
  src/pages/memory/Memory.tsx
  src/pages/notice/Notice.tsx
Labels: 🌏 Deploy

#264 develp branch 작업내용 머지 : develop -> main
  src/components/common/Layout.tsx
Labels: 🌏 Deploy

#266 develp branch 작업내용 머지 : develop -> main
  src/components/group/CompletedGroupModal.tsx
  src/components/group/MyGroupModal.tsx
Labels: 🐞 BugFix, 🌏 Deploy
