Repository THIP-TextHip/THIP-Web, pull requests merged in 2025-08, with the labels that each got.

#76 feat: 프로그레스 바 구현
  src/components/memory/MemoryContent/MemoryContent.tsx
  src/components/memory/UploadProgressBar/UploadProgressBar.tsx
  src/components/pollwrite/PollCreationSection.tsx
  src/pages/memory/Memory.tsx
  src/pages/pollwrite/PollWrite.tsx
  src/pages/recordwrite/RecordWrite.tsx
Labels: ✨ Feature, 🎨 Html&css

#102 feat: 새 글 작성 API 연동
  src/api/feeds/createFeed.ts
  src/api/feeds/getFeedDetail.ts
  src/api/feeds/getMyFeed.ts
  src/api/feeds/getOtherFeed.ts
  src/api/feeds/getTotalFeed.ts
  src/api/images/uploadImage.ts
  src/components/common/BookSearchBottomSheet/BookSearchBottomSheet.tsx
  src/components/common/Post/PostBody.tsx
  src/components/feed/FeedDetailPostBody.tsx
  src/data/postData.ts
  src/hooks/useCreateFeed.ts
  src/mocks/searchBook.mock.ts
  src/pages/post/CreatePost.tsx
  src/types/post.ts
  src/utils/isbn.ts
Labels: 📬 API

#104 feat: 피드 메인페이지 - 내 띱 목록 API 연동
  src/App.tsx
  src/api/index.ts
  src/api/recentsearch/getRecentSearch.ts
  src/api/users/getRecentFollowing.ts
  src/api/users/getUsers.ts
  src/components/feed/BookInfoCard.tsx
  src/components/feed/FollowList.tsx
  src/components/feed/UserProfileItem.tsx
  src/hooks/useOAuthToken.ts
  src/hooks/useUserSearch.ts
  src/pages/feed/Feed.tsx
  src/pages/feed/UserSearch.tsx
  src/pages/signup/SignupGenre.tsx
  src/pages/signup/SignupNickname.tsx
Labels: ✨ Feature

#115 fix: 헤더 임시 하드토큰 반영 로직 추가
  src/api/index.ts
  src/components/common/TokenStatus.tsx
  src/hooks/useOAuthToken.ts
Labels: 🐞 BugFix

#116 feat: 새 글 작성을 위한 화면 조회(카테고리, 태그 조회) API 연동
  src/api/feeds/getWriteInfo.ts
  src/components/createpost/TagSelectionSection.tsx
Labels: 📬 API

#117 feat: Rooms 도메인 API 연동
  src/api/rooms/getJoinedRooms.ts
  src/api/rooms/getMyRooms.ts
  src/api/rooms/getRoomDetail.ts
  src/api/rooms/getRoomsByCategory.ts
  src/components/group/CompletedGroupModal.tsx
  src/components/group/GroupCard.tsx
  src/components/group/MyGroupBox.tsx
  src/components/group/MyGroupModal.tsx
  src/components/group/RecruitingGroupBox.tsx
  src/pages/group/CreateGroup.tsx
  src/pages/group/Group.tsx
  src/pages/groupDetail/GroupDetail.styled.ts
  src/pages/groupDetail/GroupDetail.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 📬 API

#119 feat: 기록, 투표 생성 및 기록장 조회 API 연동
  src/api/memory/getMemoryPosts.ts
  src/api/record/createRecord.ts
  src/api/record/createVote.ts
  src/components/memory/MemoryAddButton/MemoryAddButton.tsx
  src/pages/index.tsx
  src/pages/memory/Memory.tsx
  src/pages/pollwrite/PollWrite.tsx
  src/pages/recordwrite/RecordWrite.tsx
  src/types/memory.ts
  src/types/record.ts
Labels: 📬 API

#121 feat: 저장한 책 또는 참여 중 모임의 책 조회 API 연동
  src/api/books/getSavedBooks.ts
  src/components/common/BookSearchBottomSheet/BookList.tsx
  src/components/common/BookSearchBottomSheet/BookSearchBottomSheet.styled.ts
  src/components/common/BookSearchBottomSheet/BookSearchBottomSheet.tsx
  src/components/common/BookSearchBottomSheet/BookSearchHeader.tsx
  src/components/common/BookSearchBottomSheet/BookSearchStates.tsx
  src/components/common/BookSearchBottomSheet/BookSearchTabs.tsx
  src/components/common/BookSearchBottomSheet/useBookSearch.ts
Labels: 📬 API

#126 feat: API 연동에 따른 page별 이동 이벤트 구현
  src/components/group/MyGroupBox.tsx
  src/components/group/MyGroupCard.tsx
  src/pages/group/CreateGroup.tsx
  src/pages/groupDetail/GroupDetail.tsx
  src/pages/post/CreatePost.tsx
  src/pages/searchBook/SearchBook.styled.ts
  src/pages/searchBook/SearchBook.tsx
  src/pages/searchBook/SearchBookGroup.tsx
Labels: 📬 API

#125 fix: 회원가입 튜토리얼 페이지 추가
  src/assets/signup/guide1.svg
  src/assets/signup/guide2.svg
  src/assets/signup/guide3.svg
  src/assets/signup/guide4.svg
  src/assets/signup/guide5.svg
  src/assets/signup/guide6.svg
  src/components/common/Modal/PopupContainer.tsx
  src/components/common/Modal/ReplyModal.tsx
  src/components/feed/BookInfoCard.tsx
  src/components/feed/Profile.tsx
  src/components/feed/UserProfileItem.tsx
  src/components/search/BookSearchResult.tsx
  src/pages/Guide.tsx
  src/pages/index.tsx
  src/pages/search/Search.tsx
  src/pages/signup/SignupDone.tsx
  src/pages/signup/SignupGenre.tsx
Labels: ✨ Feature, 🎨 Html&css

#144 develp branch 작업내용 머지 : develop -> main
  src/api/auth/exchangeTempToken.ts
  src/api/auth/getToken.ts
  src/api/auth/index.ts
  src/api/auth/setCookie.ts
  src/api/index.ts
  src/api/rooms/getSearchRooms.ts
  src/api/users/postSignup.ts
  src/components/group/CompletedGroupModal.tsx
  src/components/group/MyGroupBox.tsx
  src/components/group/MyGroupModal.tsx
  src/components/search/GroupSearchResult.tsx
  src/hooks/useSocialLoginToken.ts
  src/pages/feed/Feed.tsx
  src/pages/group/Group.tsx
  src/pages/groupDetail/GroupDetail.tsx
  src/pages/groupSearch/GroupSearch.tsx
  src/pages/login/Login.tsx
  src/pages/searchBook/SearchBookGroup.tsx
  src/pages/signup/SignupGenre.tsx
  src/pages/signup/SignupNickname.tsx
Labels: 🌏 Deploy

#149 feat: 비번방 입장 모달 구현
  src/api/rooms/postPassword.ts
  src/components/group/PasswordModal.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#164 fix: 책 검색 무한스크롤 로직 수정 및 최근검색어 API 수정
  src/api/recentsearch/deleteRecentSearch.ts
  src/components/search/BookSearchResult.tsx
  src/pages/feed/UserSearch.tsx
  src/pages/groupSearch/GroupSearch.tsx
  src/pages/search/Search.tsx
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#169 fix: QA 1차 완료
  src/assets/feed/lookmore.svg
  src/components/common/Layout.tsx
  src/components/common/Modal/MoreMenu.tsx
  src/components/common/Modal/Snackbar.tsx
  src/components/common/Post/PostBody.tsx
  src/components/common/Post/PostFooter.tsx
  src/components/common/Post/PostHeader.tsx
  src/components/common/Post/ReplyList.tsx
  src/components/common/ScrollToTop.tsx
  src/components/feed/BookInfoCard.tsx
  src/components/feed/FeedDetailPost.tsx
  src/components/feed/FeedDetailPostBody.tsx
  src/components/feed/FeedPost.tsx
  src/components/feed/FollowList.tsx
  src/components/feed/MyFeed.tsx
  src/components/feed/MyFollower.tsx
  src/components/feed/Profile.tsx
  src/components/feed/TabBar.tsx
  src/components/feed/TotalBar.tsx
  src/components/feed/TotalFeed.tsx
  src/components/feed/UserProfileItem.tsx
  src/pages/feed/FeedDetailPage.tsx
  src/pages/feed/FollowerListPage.tsx
  src/pages/feed/UserSearchResult.tsx
  src/pages/index.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/signup/Signup.styled.ts
  src/pages/signup/SignupDone.tsx
  src/pages/signup/SignupGenre.tsx
Labels: 🐞 BugFix

#172 fix: QA 2차 수정
  index.html
  public/assets/custom_favicon.png
  public/assets/thumbnail.jpeg
  public/assets/thumbnail.png
  src/components/common/Post/PostBody.tsx
  src/components/feed/FollowList.tsx
  src/components/feed/MyFeed.tsx
  src/pages/feed/Feed.tsx
  src/pages/mypage/Mypage.tsx
Labels: 🐞 BugFix

#179 fix: 1차 QA
  src/assets/memory/record-x.svg
  src/components/common/CommentBottomSheet/GlobalCommentBottomSheet.styled.ts
  src/components/common/Modal/MoreMenu.tsx
  src/components/common/Modal/Snackbar.tsx
  src/components/creategroup/ActivityPeriodSection/ActivityPeriodSection.styled.ts
  src/components/creategroup/ActivityPeriodSection/ActivityPeriodSection.tsx
  src/components/creategroup/RoomInfoSection.styled.ts
  src/components/creategroup/RoomInfoSection.tsx
  src/components/createpost/PostContentSection.styled.ts
  src/components/createpost/PostContentSection.tsx
  src/components/group/CommentSection.styled.ts
  src/components/group/GroupBookSection.styled.ts
  src/components/group/GroupBookSection.tsx
  src/components/group/HotTopicSection.styled.ts
  src/components/group/MyGroupCard.tsx
  src/components/group/RecordSection.styled.ts
  src/components/group/RecordSection.tsx
  src/components/memory/MemoryContent/MemoryContent.styled.ts
  src/components/memory/MemoryContent/MemoryContent.tsx
  src/components/memory/MemoryContent/RecordList.styled.ts
  src/components/memory/MemoryContent/RecordList.tsx
  src/components/memory/PageRangeModal.styled.ts
  src/components/memory/PageRangeModal.tsx
  src/components/memory/RecordFilters/FilterButtons.styled.ts
  src/components/memory/RecordFilters/FilterButtons.tsx
  src/components/memory/RecordFilters/PageInputMode.styled.ts
  src/components/memory/RecordFilters/PageInputMode.tsx
  src/components/memory/RecordFilters/RecordFilters.tsx
  src/components/memory/RecordInfoMessage.tsx
  src/components/memory/RecordItem/PollRecord.tsx
  src/components/memory/RecordItem/RecordItem.tsx
  src/components/recordwrite/PageRangeSection.styled.ts
  src/components/recordwrite/PageRangeSection.tsx
  src/pages/group/CreateGroup.tsx
  src/pages/groupDetail/GroupDetail.styled.ts
  src/pages/groupDetail/ParticipatedGroupDetail.styled.ts
  src/pages/groupDetail/ParticipatedGroupDetail.tsx
  src/pages/memory/Memory.tsx
  src/pages/post/CreatePost.tsx
  src/pages/post/UpdatePost.tsx
  src/pages/today-words/TodayWords.tsx
  src/stores/usePopupStore.ts
  src/types/memory.ts
Labels: 🐞 BugFix

#178 fix: QA 3차
  src/components/common/LoadingSpinner.tsx
  src/components/common/Post/PostBody.tsx
  src/components/common/Post/PostFooter.tsx
  src/components/feed/FeedPost.tsx
  src/components/feed/UserProfileItem.tsx
  src/components/group/Modal.styles.ts
  src/pages/feed/FollowerListPage.tsx
  src/pages/mypage/SavePage.tsx
  src/pages/searchBook/SearchBook.tsx
  src/types/follow.ts
  src/types/post.ts
  src/types/user.ts
Labels: 🐞 BugFix

#180 develp branch 작업내용 머지 : develop -> main
  src/assets/memory/record-x.svg
  src/components/common/CommentBottomSheet/GlobalCommentBottomSheet.styled.ts
  src/components/common/LoadingSpinner.tsx
  src/components/common/Modal/MoreMenu.tsx
  src/components/common/Modal/Snackbar.tsx
  src/components/common/Post/PostBody.tsx
  src/components/common/Post/PostFooter.tsx
  src/components/creategroup/ActivityPeriodSection/ActivityPeriodSection.styled.ts
  src/components/creategroup/ActivityPeriodSection/ActivityPeriodSection.tsx
  src/components/creategroup/RoomInfoSection.styled.ts
  src/components/creategroup/RoomInfoSection.tsx
  src/components/createpost/PostContentSection.styled.ts
  src/components/createpost/PostContentSection.tsx
  src/components/feed/FeedPost.tsx
  src/components/feed/UserProfileItem.tsx
  src/components/group/CommentSection.styled.ts
  src/components/group/GroupBookSection.styled.ts
  src/components/group/GroupBookSection.tsx
  src/components/group/HotTopicSection.styled.ts
  src/components/group/Modal.styles.ts
  src/components/group/MyGroupCard.tsx
  src/components/group/RecordSection.styled.ts
  src/components/group/RecordSection.tsx
  src/components/memory/MemoryContent/MemoryContent.styled.ts
  src/components/memory/MemoryContent/MemoryContent.tsx
  src/components/memory/MemoryContent/RecordList.styled.ts
  src/components/memory/MemoryContent/RecordList.tsx
  src/components/memory/PageRangeModal.styled.ts
  src/components/memory/PageRangeModal.tsx
  src/components/memory/RecordFilters/FilterButtons.styled.ts
  src/components/memory/RecordFilters/FilterButtons.tsx
  src/components/memory/RecordFilters/PageInputMode.styled.ts
  src/components/memory/RecordFilters/PageInputMode.tsx
  src/components/memory/RecordFilters/RecordFilters.tsx
  src/components/memory/RecordInfoMessage.tsx
  src/components/memory/RecordItem/PollRecord.tsx
  src/components/memory/RecordItem/RecordItem.tsx
  src/components/recordwrite/PageRangeSection.styled.ts
  src/components/recordwrite/PageRangeSection.tsx
  src/pages/feed/FollowerListPage.tsx
  src/pages/group/CreateGroup.tsx
  src/pages/groupDetail/GroupDetail.styled.ts
  src/pages/groupDetail/ParticipatedGroupDetail.styled.ts
  src/pages/groupDetail/ParticipatedGroupDetail.tsx
  src/pages/memory/Memory.tsx
  src/pages/mypage/SavePage.tsx
  src/pages/post/CreatePost.tsx
  src/pages/post/UpdatePost.tsx
  src/pages/searchBook/SearchBook.tsx
  src/pages/today-words/TodayWords.tsx
  src/stores/usePopupStore.ts
  src/types/follow.ts
  src/types/memory.ts
  src/types/post.ts
  src/types/user.ts
Labels: 🌏 Deploy

#182 develp branch 작업내용 머지 : develop -> main
  src/components/feed/OtherFeed.tsx
  src/components/feed/UserProfileItem.tsx
  src/pages/feed/MyFeedPage.tsx
Labels: 🐞 BugFix

#187 hotjar 웹사이트 히트맵 서비스 추가
  index.html
Labels: 🌏 Deploy

#194 main 배포
  src/api/rooms/getRoomDetail.ts
  src/api/rooms/getRoomMembers.ts
  src/api/rooms/getRoomPlaying.ts
  src/components/creategroup/ActivityPeriodSection/ActivityPeriodSection.tsx
  src/components/creategroup/GenreSelectionSection.tsx
  src/components/creategroup/MemberLimitSection.tsx
  src/components/creategroup/PrivacySettingSection/PrivacySettingSection.tsx
  src/components/creategroup/RoomInfoSection.tsx
  src/components/group/CommentSection.styled.ts
  src/components/group/CommentSection.tsx
  src/components/group/RecordSection.styled.ts
  src/components/group/RecordSection.tsx
  src/components/memory/RecordItem/RecordItem.tsx
  src/pages/groupDetail/GroupDetail.tsx
  src/pages/groupDetail/ParticipatedGroupDetail.tsx
  src/pages/groupMembers/GroupMembers.tsx
  src/pages/post/UpdatePost.tsx
Labels: 🌏 Deploy

#197 develp branch 작업내용 머지 : develop -> main
  src/components/common/Post/PostBody.tsx
  src/components/feed/FeedDetailPostBody.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/signup/SignupGenre.tsx
  src/styles/global/global.ts
Labels: 🌏 Deploy

#202 Deploy: main에 배포
  src/api/rooms/getRoomMembers.ts
  src/components/common/BookSearchBottomSheet/BookSearchBottomSheet.styled.ts
  src/components/creategroup/RoomInfoSection.styled.ts
  src/components/createpost/PhotoSection.tsx
  src/components/createpost/PostContentSection.styled.ts
  src/components/members/MemberList.tsx
  src/components/recordwrite/PageRangeSection.styled.ts
  src/pages/groupMembers/GroupMembers.tsx
  src/pages/pollwrite/PollWrite.styled.ts
  src/pages/recordwrite/RecordWrite.styled.ts
Labels: 🌏 Deploy

#211 fix: 내 피드 > 프로필 > 띱 목록 조회 안되는 이슈 수정
  src/components/feed/MyFeed.tsx
  src/types/profile.ts
Labels: 🐞 BugFix
